name: MetaOSController Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow_ref }}-${{ github.job }}_${{ matrix.container }}-${{ matrix.compiler }}-${{ matrix.variant }}
    container: ${{ matrix.container }}

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++
        container:
          - ubuntu:24.04
        variant:
          - libuv
          - asio
        include:
          - compiler: g++
            dependencies: g++
          - variant: asio
            cmake_args: -DGRPCXX_USE_ASIO=ON

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This is the corrected step for installing dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ${{ matrix.dependencies }} \
            cmake ninja-build \
            libprotobuf-dev libprotoc-dev protobuf-compiler
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: |
          cmake -B .build -G Ninja \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DGRPCXX_BUILD_EXAMPLES=OFF \
            -DGRPCXX_BUILD_EXPERIMENTS=OFF \
            ${{ matrix.cmake_args }}
      - name: Build
        run: cmake --build .build