name: MetaOSController Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        variant: [asio]
        include:
          - variant: asio
            dependencies: "libgrpc++-dev libprotobuf-dev protobuf-compiler libgtest-dev"
            cmake_args: "-DGRPCXX_USE_ASIO=ON"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build g++ libgtest-dev libgrpc++-dev libprotobuf-dev protobuf-compiler protobuf-compiler-grpc

      - name: Configure CMake
        run: cmake -S . -B .build -G Ninja -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake_args }}

      - name: Build
        run: cmake --build .build --config Release

      - name: Test
        run: echo "Placeholder for future gtest tests"
