name: MetaOSController Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This is the corrected step for installing dependencies
      - name: Install dependencies with vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'e8b25b658a20675844a43477156976937589e494'
          
      - name: Configure CMake
        run: |
          # The run-vcpkg action automatically sets the CMAKE_TOOLCHAIN_FILE env variable
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_SERVER_TESTS=ON

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
